import os,sys,json,types,tempfile
os.environ['MPLBACKEND']='Agg'
import numpy as np,pandas as pd
import matplotlib.pyplot as plt

# Local sandbox lacks IPython; Kaggle provides it. Mock display only for regression testing.
ipython_mod=types.ModuleType('IPython')
ipython_mod.get_ipython=lambda: None
ipython_mod.version_info=(9,0)
display_mod=types.ModuleType('IPython.display')
display_mod.display=lambda *args,**kwargs: None
display_mod.HTML=lambda value: value
display_mod.clear_output=lambda *args,**kwargs: None
ipython_mod.display=display_mod
sys.modules['IPython']=ipython_mod
sys.modules['IPython.display']=display_mod

class DummyYF:
    def download(self,*args,**kwargs): return pd.DataFrame()
sys.modules['yfinance']=DummyYF()

nb=json.load(open('/data/crypto_sentinel_live_UI_kaggle.ipynb'))
ns={}
for idx in [2,3,4,5,6,7]: exec(''.join(nb['cells'][idx]['source']),ns)

work='/data/ui_test_runtime'
os.makedirs(work,exist_ok=True)
for name in os.listdir(work):
    path=os.path.join(work,name)
    if os.path.isfile(path): os.remove(path)
ns['BASE_DIR']=work
for key,file in [('STATE_FILE','state.json'),('TRADES_FILE','trades.csv'),('SIGNALS_FILE','signals.csv'),('EQUITY_FILE','equity.csv'),('REPORT_PNG','report.png')]: ns[key]=os.path.join(work,file)

n=800;rng=np.random.default_rng(4);idx=pd.date_range('2026-08-01',periods=n,freq='5min',tz='UTC')
ret=0.00008+0.0015*np.sin(np.arange(n)/21)+rng.normal(0,0.0012,n)
close=62000*np.exp(np.cumsum(ret))
raw=pd.DataFrame({'Open':close,'High':close*1.0015,'Low':close*.9985,'Close':close,'Volume':rng.lognormal(8,.5,n)},index=idx)
feature=ns['indicators'](raw);latest=float(feature.Close.iloc[-1]);atr=float(feature.atr.iloc[-1])
ranked=[
 {'symbol':'BTC-USD','price':latest,'score':78.4,'regime':'uptrend','ml_probability':.641,'ml_accuracy':.552,'ml_auc':.574,'learned_ready':True,'atr':atr,'rsi':58,'learning_rows':720,'reasons':'trend','candle':str(idx[-1])},
 {'symbol':'ETH-USD','price':3450.22,'score':66.2,'regime':'range','ml_probability':.533,'ml_accuracy':.521,'ml_auc':.538,'learned_ready':True,'atr':32,'rsi':52,'learning_rows':718,'reasons':'range','candle':str(idx[-1])},
 {'symbol':'SOL-USD','price':148.37,'score':51.8,'regime':'high_volatility','ml_probability':.487,'ml_accuracy':.493,'ml_auc':.498,'learned_ready':False,'atr':3.2,'rsi':44,'learning_rows':715,'reasons':'volatility','candle':str(idx[-1])}
]
state=ns['fresh_state']()
# Create one completed BUY/SELL trade so table and markers are exercised.
setup={'symbol':'BTC-USD','price':latest*.97,'atr':atr,'score':74}
ns['enter'](state,setup)
# Put historical timestamps inside chart range for markers.
state['position']['opened_at']=str(idx[-80])
ns['exit_position'](state,latest*.985,'take_profit_test')
trades=pd.read_csv(ns['TRADES_FILE']);trades.loc[0,'opened_at']=str(idx[-80]);trades.loc[0,'closed_at']=str(idx[-45]);trades.loc[0,'entry']=float(raw.Close.iloc[-80]);trades.loc[0,'exit']=float(raw.Close.iloc[-45]);trades.to_csv(ns['TRADES_FILE'],index=False)
# Open a current position to exercise balance, stop, target and live marker.
ns['enter'](state,{'symbol':'BTC-USD','price':latest*.995,'atr':atr,'score':78.4})
state['position']['opened_at']=str(idx[-15]);state['position']['entry']=float(raw.Close.iloc[-15])
last_prices={'BTC-USD':latest,'ETH-USD':3450.22,'SOL-USD':148.37}
html=ns['build_dashboard_html'](state,ranked,last_prices,'Managing open BTC-USD paper position')
assert 'Total equity' in html and 'Recent completed trades' in html and 'BUY' in html
assert 'BTC-USD' in html and 'PAPER TRADING' in html and 'take_profit_test' in html
assert 'label="SELL"' in ''.join(nb['cells'][7]['source'])
open('/data/live_dashboard_preview.html','w').write(html)
# Save the chart generated by the exact notebook function.
original_show=plt.show
plt.show=lambda *a,**k: plt.savefig('/data/live_trade_chart_preview.png',dpi=150,bbox_inches='tight')
ns['plot_live_trade_chart'](state,ranked,{'BTC-USD':raw,'ETH-USD':raw,'SOL-USD':raw})
plt.show=original_show
assert os.path.exists('/data/live_trade_chart_preview.png')
print('UI TESTS PASSED')
